version: "3.9"

networks:
  iis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  srcei:
    container_name: srcei_container
    build:
      context: IIS_servicios_SRCEI
      dockerfile: IIS_servicios_common/Dockerfile
      args:
        API_PORT: ${API_PORT_SRCEI}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    ports:
      - "${API_PORT_SRCEI}:${API_PORT_SRCEI}"
    networks:
      iis-net:
        ipv4_address: 10.5.0.2
    restart: "always"
    volumes: []

  caja:
    container_name: caja_container
    build:
      context: IIS_servicios_Caja
      dockerfile: IIS_servicios_common/Dockerfile
      args:
        API_PORT: ${API_PORT_CAJA}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    ports:
      - "${API_PORT_CAJA}:${API_PORT_CAJA}"
    networks:
      iis-net:
        ipv4_address: 10.5.0.3
    restart: "always"
    volumes: []
  
  # rvm:
  #   container_name: rvm_container
  #   build:
  #     context: IIS_servicios_RVM
  #     dockerfile: IIS_servicios_common/Dockerfile
  #     args:
  #       API_PORT: ${API_PORT_RVM}
  #       UBUNTU_VERSION: ${UBUNTU_VERSION}
  #   ports:
  #     - "${API_PORT_RVM}:${API_PORT_RVM}"
  #   networks:
  #     iis-net:
  #       ipv4_address: 10.5.0.4
  #   restart: "always"
  #   volumes: []

  ppe:
    container_name: ppe_container
    build:
      context: IIS_servicios_PPE
      dockerfile: IIS_servicios_common/Dockerfile
      args:
        API_PORT: ${API_PORT_PPE}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    ports:
      - "${API_PORT_PPE}:${API_PORT_PPE}"
    networks:
      iis-net:
        ipv4_address: 10.5.0.5
    restart: "always"
    volumes: []